services:
  postgres:
    container_name: recipe_postgres-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 2s
      retries: 15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  flyway:
    container_name: recipe_flyway-migrations
    image: flyway/flyway:11
    command: -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/migrations/:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/postgres
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=secret
    depends_on:
      postgres:
        condition: service_healthy

  api:
    image: recipe-api
    container_name: recipe-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      API_SERVICE_PORT: 8080
      DB_NAME: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: secret
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
